### ISSUE TITLE
Timeout database query 30min Business Central.

### ISSUE THREAD

**Issue by italfapeopleco** [microsoft/bc2adls#105]
I need to export a table from Business Central (GLEntry-17), but it currently weighs 23 GB and the query takes more than 30 min because it is canceled automatically, checking the Business Central limits, I see that there are Query limits at the standard level, what could be done to fix this?

https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/operational-limits-online#query-limits

![Captura de pantalla 2023-03-29 223910](https://user-images.githubusercontent.com/99347818/228722628-8821f617-6035-40a5-a996-8f0cd1bd4e70.png)

"An unexpected error occurred after canceling a database command."ADLSE Seek Data"(Report 82560)."Number - OnAfterGetRecord"(Trigger) line 5 - Azure Data Lake Storage Export by The bc2adls team, Microsoft Denmark\" ADLSE Seek Data"(Report 82560).GetResult line 4: Azure Data Lake Storage Export by The bc2adls team, Microsoft Denmark\"ADLSE Seek Data"(Report 82560).FindRecords line 3 - Azure Data Lake Storage Export by The bc2adls team, Microsoft Denmark\"ADLSE Execute"(CodeUnit 82561).ExportTableUpdates line 22 - Azure Data Lake Storage export by The bc2adls team, Microsoft Denmark\"ADLSE Execute"(CodeUnit 82561).TryExportTableData line 12 - Azure Data Lake Storage export by The bc2adls team, Microsoft Denmark\"ADLSE Execute"(CodeUnit 82561).OnRun(Trigger) line 47 - Azure Data Lake Storage Export by The bc2adls team, Microsoft Denmark\"

**Comment by DuttaSoumya** [comment]
Thanks @italfapeopleco for raising this. In order to isolate this issue and find its root cause, may I please ask you to make this _**temporary**_ change to the procedure [SetFilterForUpdates](https://github.com/microsoft/bc2adls/blob/main/businessCentral/src/ADLSEExecute.Codeunit.al#:~:text=local%20procedure-,SetFilterForUpdates), and let us know how the export went for the `G/L Entry` table?

    local procedure SetFilterForUpdates(TableID: Integer; UpdatedLastTimeStamp: BigInteger; var Rec: RecordRef; var TimeStampField: FieldRef)
    begin
        Rec.Open(TableID); 
        //Rec.SetView(TimestampAscendingSortViewTxt);
        TimeStampField := Rec.Field(0); // 0 is the TimeStamp field
        TimeStampField.SetFilter('>%1', UpdatedLastTimestamp);
    end;`

**Comment by italfapeopleco** [comment]
Hello Dutta, thanks for help.

The query cancellation error is gone, but now I'm getting this message in the same table.

"Could not commit blocks to https://dapcolexporttodatalakepr.blob.core.windows.net/boldpr/deltas/GLEntry-17/9680BF30-41B6-496B-B824-4A19E6BD8565.csv. <?xml version="1.0" encoding="utf-8"?><Error><Code>OperationTimedOut</Code><Message>Operation could not be completed within the specified time. RequestId:86ceb695-401e-00f1-6e7b-6323d9000000 Time:2023-03-31T02:51:20.2790517Z</Message></Error>"ADLSE Gen 2 Util"(CodeUnit 82568).CommitAllBlocksOnDataBlob line 18 - Azure Data Lake Storage Export by The bc2adls team, Microsoft Denmark\"ADLSE Communication"(CodeUnit 82562).FlushPayload line 23 - Azure Data Lake Storage Export by The bc2adls team, Microsoft Denmark\"ADLSE Communication"(CodeUnit 82562).CollectAndSendRecord line 14 - Azure Data Lake Storage Export by The bc2adls team, Microsoft Denmark\"ADLSE Communication"(CodeUnit 82562).TryCollectAndSendRecord line 4 - Azure Data Lake Storage Export by The bc2adls team, Microsoft Denmark\"ADLSE Execute"(CodeUnit 82561).ExportTableUpdates line 38 - Azure Data Lake Storage Export by The bc2adls team, Microsoft Denmark\"ADLSE Execute"(CodeUnit 82561).TryExportTableData line 12 - Azure Data Lake Storage Export by The bc2adls team, Microsoft Denmark\"ADLSE Execute"(CodeUnit 82561).OnRun(Trigger) line 47 - Azure Data Lake Storage Export by The bc2adls team, Microsoft Denmark\"ADLSE Execute"(CodeUnit 82561).ExportTableUpdates line 41 - Azure Data Lake Storage Export by The bc2adls team, Microsoft Denmark\"ADLSE Execute"(CodeUnit 82561).TryExportTableData line 12 - Azure Data Lake Storage Export by The bc2adls team, Microsoft Denmark\"ADLSE Execute"(CodeUnit 82561).OnRun(Trigger) line 47 - Azure Data Lake Storage Export by The bc2adls team, Microsoft Denmark\"

**Comment by DuttaSoumya** [comment]
Hi @italfapeopleco,

First of all, good to know that we have been able to isolate your issue on pushing the increments to the lake. We are working on a "proper" fix that will be applied soon here.

Meanwhile with reference to the new error you get, The issue comes from a REST API to the blob storage timing out from the procedure [CommitAllBlocksOnDataBlob](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fbc2adls%2Fblob%2Fmain%2FbusinessCentral%2Fsrc%2FADLSEGen2Util.Codeunit.al%23%3A~%3Atext%3DCommitAllBlocksOnDataBlob&data=05%7C01%7CSoumya.Dutta%40microsoft.com%7Cdf87a6c4f3ce4e594d1b08db291d0725%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638148976878878880%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WiumvwM73hIlIoZs4Z6ZFBiSdIouTF9P9v8rcpDTDDc%3D&reserved=0). We are using default timeouts in the bc2adls app, but you may add [additional timeout URL parameter](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Frest%2Fapi%2Fstorageservices%2Fput-block-list%3Ftabs%3Dazure-ad%23%3A~%3Atext%3DDescription-%2Ctimeout%2C-Optional.%2520The%2520timeout&data=05%7C01%7CSoumya.Dutta%40microsoft.com%7Cdf87a6c4f3ce4e594d1b08db291d0725%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638148976878878880%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=d72VvvHriD7HNrwNHr5fe4bQQzesK0rLtM%2Bwe0GjQrQ%3D&reserved=0) if you want by suffixing the URL call with `?timeout=XX`, XX being the number of seconds for timeout to expire. This issue could typically happen when you are pushing a large payload to the server. Consider reducing the number at the field [Max payload size (MiBs)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fbc2adls%2Fblob%2Fmain%2F.assets%2FSetup.md%23%3A~%3Atext%3DMax%2520payload%2520size%2520(MiBs)&data=05%7C01%7CSoumya.Dutta%40microsoft.com%7Cdf87a6c4f3ce4e594d1b08db291d0725%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638148976878878880%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FFVvib4p8Vejr2qgkrk%2FulbM%2BtOM%2BReGC%2F%2FevrBMqUM%3D&reserved=0).

As always, we would be keen to know how you solve the problem here and if we could learn/ apply that solution ourselves? :-)

Best regards,
Dutta.

**Comment by DuttaSoumya** [comment]
Thanks for the update!

**Comment by DuttaSoumya** [comment]
A new pull request has been created to handle such cases, without the user fixing it in code. 
[Pull request #109](https://github.com/microsoft/bc2adls/pull/109)

@italfapeopleco , I would be much obliged if you would take this for a spin.

Note: Please refer to the [ErrorDuringExportShouldSaveLastExportedTimestamp](https://github.com/microsoft/bc2adls/tree/ErrorDuringExportShouldSaveLastExportedTimestamp) branch.

Two issues addressed, 
1. Exporting large amounts of data to the lake caused a query timeout issue when sorting the records as per the row version. Sorting is important as it helps ensure that the subsequent exports restart from records which were **not** exported during the last run. The timeout issue was caused by this sorting over large number of records. So a new flag called **Skip row version sorting** is introduced on the setup page that allows unsorted records to be uploaded to the lake. This is to be used only as a temporary measure and should be disabled once the data has been uploaded to the lake. See [documentation for the field](/.assets/Setup.md). 
1. An error occurring late in the export process forces the system to start from the first record when the export is invoked again. So the system has been made robust by saving the last timestamps even in case of errors. This helps subsequent exports to "catch up" from the time the last export went into the lake.

**Comment by italfapeopleco** [comment]
Hello DuttaSoumya. For me it is a pleasure to collaborate with you, as you do with all of us, to give continuity to this procedure of movement of massive data, I have found another problem when consolidating the entities that have a very large size.

When the data pipeline process runs, the system may display the following error:

![image](https://user-images.githubusercontent.com/99347818/229575036-8921d5fd-cae9-46f4-a279-9f2247d95da5.png)

_"Job failed due to reason: at Sink 'StagingParquet': Failed to execute dataflow with internal server error, please retry later. If issue persists, please contact Microsoft support for further assistance. Details:org.apache.spark.SparkException: Job aborted due to stage failure: Task 195 in stage 9.0 failed 1 times, most recent failure: Lost task 195.0 in stage 9.0 (TID 801, vm-13f69576, executor 1): ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Container from a bad node: container_1680446369595_0001_01_000002 on host: vm-13f69576. Exit status: 143. Diagnostics: [2023-04-02 14:56:46.637]Container killed on request. Exit code is 143\n[2023-04-02 14:56:46.638]Container exited with a non-zero exit code 143. \n[2023-04-02 14:56:46.640]Killed by external signal\n.\nDriver stacktrace:\n\tat com.microsoft.dataflow.FileStoreExceptionHandler$.extractRootCause(FileStoreExceptionHandler.scala:36)\n\tat com.microsoft.dataflow.transformers.DefaultFileWriter$$anonfun$write$1$$anonfun$103$$anonfun$apply$94$$anonfun$apply$5.apply$mcV$sp(FileStore.scala:1193)\n\tat com.microsoft.dataflow.transformers.DefaultFileWriter$$anonfun$write$1$$anonfun$103$$anonfun$apply$94$$anonfun$apply$5.apply(FileStore.scala:1168","failureType":"UserError","target":"ConsolidationDF_staging","errorCode":"DF-Executor-InternalServerError"_



**I have solved this problem by increasing the compute size of the data stream. It was originally in "small" but I changed it to "Medium" (8 (+ 8 Driver cores))**

![image](https://user-images.githubusercontent.com/99347818/229575529-f919db7a-fbbb-4e5e-952c-47156275c222.png)

**Comment by DuttaSoumya** [comment]
May I please persuade you to report the new issue under a separate thread, @italfapeopleco? That way our administration on the topics becomes easier. :-)

Also, thanks for sharing that you have been able to work around it by increasing Compute Size.
