### ISSUE TITLE
What's the current status?

### ISSUE THREAD

**Issue by deadmouse** [microsoft/bc2adls#45]
I would like to know the current status of this project. 

Is there any roadmap where we can know how this project is advancing? Do you expect this project to be stable in a near future? Is it reliable to use it in a Production environment nowadays?

Thank you

**Comment by HenriSchulte-MS** [comment]
Hi deadmouse,
while we don't have any sort of roadmap, we are constantly improving bc2adls. Currently, I am working on extending the possibilities of interacting with bc2adls data in SQL and Spark. Since bc2adls is open source, you are welcome to make your own additions and contribute to the repository.
Please bear in mind that bc2adls is a prototype and that there are currently no plans to integrate it into any official Microsoft product. I would encourage you try it out and see whether it meets your requirements. If you run into issues, you are welcome to reach out at bc2adls@microsoft.com.
