### ISSUE TITLE
Enum Ids and Field Captions

### ISSUE THREAD

**Issue by JulianSchmidtke** [microsoft/bc2adls#67]
Our BI Solution for OnPrem uses Option and Enum IDs  to Map Values. 
We would like to have a numerical mapping for multi language support, too. 

When exporting a Table field of type enum it is exported like

CDN:
```
{
    "name": "DocumentType-1",
    "dataFormat": "String",
    "appliedTraits": [],
    "displayName": "Document Type"
},
```

CSV:
```
DocumentType-1
--
Quote
Quote
Order
```

I would like to have the following information:
1. The available Field Translations
2. A Mapping from Enum Id to Enum Name

I tried to export Metadata Tables like `Table Metadata` but that only gives me only table but no field information.

**Comment by DuttaSoumya** [comment]
Great idea @JulianSchmidtke! The enum value goes out into the lake in the default language. For those users in Power BI who wish to have the enum value in the local language, we have been advising them to manually create a reference translation table in Power BI for each enum, with all the translations and instead of directly showing the column from the data lake, create a calculated column, and based on the language of the report, pick the right translation from the reference table.  

In most cases, the number of enums being used is limited and such a one-time setup suffices, which is why we are not prioritizing this high.

**Comment by JulianSchmidtke** [comment]
I don't think thats enough for us.

This App is amazing. We can define our own tables and our own fields, but when we export enums just the value is exported. 
BI Engineers have no way to see the possible values of our enums, but have to ask us or look into BC. What we need is a standalone solution in which the CDM exactly shows the possible Enum Values.

**Comment by DuttaSoumya** [comment]
You are right that getting all the possible values in a enum field requires a BC- aware professional. But, we believe that this configuration can be made once for many export runs.

There is an additional complication as well. The enum values possible for a field can change- depending on if an added extension extends an Enum field with its own members, or if a previous extension removes those them. This is why the schema of a field can potentially undergo constant flux. And the schema needs to be synced each time that happens. All this is too much additional responsibility on the bc2adls tool. However we are welcome to have a dialog with you if you are considering implementing this feature yourself. Please write to us at bc2adls@microsoft.com.
