### ISSUE TITLE
Naming of the Deltas

### ISSUE THREAD

**Issue by JulianSchmidtke** [microsoft/bc2adls#70]
We are planning to start with a small Data Lake: Delta Sync and then small Azure Functions to update a SQL Server. No Synapse Piplines etc.

In Dynamics F&O the Deltas are handled through the ChangeFeed. Each CSV in the Change Feed has a unique name containing the SQL LSN (Logical Sequence Number): https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/azure-data-lake-change-feeds

In this app, deltas are named by a guid. I was wondering if we might add a LSN / Hex Representation of the Timestamps in BC, too. That way we could import Deltas alphabetically.

**Comment by DuttaSoumya** [comment]
You could still import the deltas CSV files in the order of their creation by sorting the contents of the entity folder in ascending order of [the LastModified property](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.blobproperties.lastmodified?view=azure-dotnet) of the blob storage. The only architecture requirement considering the naming of the blobs is that they should be unique- that's why we name them as GUIDs.
