### ISSUE TITLE
Why do we export Table and Field IDs?

### ISSUE THREAD

**Issue by JulianSchmidtke** [microsoft/bc2adls#71]
Other Systems Export Entities by their name only. They would only export ItemledgerEntry.cdm.json instead of ItemLedgerEntry-**32**.cdm.json

Our BI engineers were wondering why we have to export the id in the name of the Entity. So I'm wondering, too: Wouldn't it be better to create custom Key/Value Attributes (BusinessCentralId) that represent the Id? That way the entities have the same name as the tables in BC.

**Comment by DuttaSoumya** [comment]
There are restrictions on the field names that Synapse can consume, for example on special characters that Business Central actually allows. This is why the field names remove those special characters and in order to differentiate the fields from each other, suffix a field ID. So if a table (in theory) has two fields these would be named differently on the data lake.
Name|ID|bc2adls Field ID
---|--|---
No.|1|No-1
No|2|No-2

... and similarly for tables as well.

However, the display name in CDM mentions the name as it gets defined in Business Central. The entity json file has the field names at /definitions[0]/hasAttributes/, say, 
![image](https://user-images.githubusercontent.com/38040179/206684468-ab857da0-8b7d-40ea-a539-d71068f46627.png)
