### ISSUE TITLE
Flag file at the end of the BC2ADLS export process

### ISSUE THREAD

**Issue by bbonekamp** [microsoft/bc2adls#84]
In order to save time between starting the Synapse Pipelines and the export from BC2ADLS, a flag file would help to know if the export process from BC2ADLS is finished.

Such a file could be monitored by Synapse in order to start the pipelines once it is e.g. renewed.

**Comment by DuttaSoumya** [comment]
Hi @bbonekamp,

We could raise a new event whenever an export for a table completes and you may subscribe to it in code and then start the pipeline. Would that help?

However the event will be raised once from different sessions for each table and for each company (in case you are exporting with the flag [Multi- Company Export](https://github.com/microsoft/bc2adls/blob/main/.assets/Setup.md#:~:text=Multi%2D%20company%20export) enabled). You will have to accumulate the number of exports completed and determine the best time to run the pipeline. Remember that the pipeline should be run when no exports from any company are underway.

Best regards,
Dutta.

**Comment by bbonekamp** [comment]
Hi @DuttaSoumya ,

Our preferred solution would be a file at the end of the export process, eventually per company. Currently we have built a pipeline that is triggered based on the event of writing a file to the delta folder (and the condition that metadata is not changed for X seconds).

If one flag file (per company) is not possible in the export, I think we would prefer our event based solution.

Regards,

Bas

**Comment by DuttaSoumya** [comment]
On second thoughts, the event based solution may not fly because the events would be raised in individual export sessions different from the main session. There would be no way to subscribe to events in other sessions than one's own. 

So, as discussed, the options remaining are the following,
-  Expose the procedure [AreAnySessionsActive ](https://github.com/microsoft/bc2adls/blob/1e21a2c6c6c8f9c7afc8fe87be25769ff04ad205/businessCentral/src/ADLSECurrentSession.Table.al#:~:text=procedure-,AreAnySessionsActive,-()%20AnyActive%3A) on the table "ADLSE Current Session" by either making it public or creating an API for it.
- Observe changes to the field [State](https://github.com/microsoft/bc2adls/blob/main/businessCentral/src/ADLSERun.Table.al#:~:text=(4%3B-,State,-%3B%20Enum%20%22ADLSE)) on the table "ADLSE Run" to either `Failed` or `Success` that would indicate completion of an export process for a table.
