### ISSUE TITLE
Truncation and Comparing Records Counts from BC to ADL

### ISSUE THREAD

**Issue by tglink72** [microsoft/bc2adls#91]
Hello,

        We have been having issues with truncation of some data during the export process.  The export reports success, but the delta and data tables do not contain records consistent with what we are seeing in BC. We are trying to develop a process to better identify when this occurs. We noticed the TableInformationCache-8700 is an entity that can be added to the export. We were hoping to use that table to then compare the cached record count with the record count we have in Synapse. 

You do not have sufficient permissions to read from the table."ADLSE Execute"(CodeUnit 66056).ExportTableUpdates line 17 - BC2ADLS "ADLSE ExecuteSSI"(CodeUnit 66056).TryExportTableData line 12 - "ADLSE ExecuteSSI"(CodeUnit 66056).OnRun(Trigger) line 46 - 

Is this table able to be exported? We have tried in a newer version of the BC2ADL tool and while it doesn't error, the table also does not seem to initiate staying in the Last Exported State of "Never Run", although it is enabled in the export. Thanks for any help!

Tom

**Comment by DuttaSoumya** [comment]
Please note that the table [Table Information Cache](https://github.com/microsoft/ALAppExtensions/blob/main/Modules/System/Table%20Information/src/TableInformationCache.Table.al) is not exposed outside the module [Table Information](https://github.com/microsoft/ALAppExtensions/tree/main/Modules/System/Table%20Information). So while you are able to select it for export, the bc2adls extension cannot access its data. Note:
![image](https://user-images.githubusercontent.com/38040179/215801972-b0e82c0b-a9f3-418f-9038-fba9682f5fb7.png)

This is By Design as per [this documentation](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-access-property#:~:text=runtime%20version%201.0-,The%20object%20can%20be%20accessed%20only%20by%20code%20in%20the%20same%20module%2C%20but%20not%20from%20another%20module.,-Table%20field%20level).
