### ISSUE TITLE
Filtering Record before exporting to ADLS

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/bc2adls#94]
Should be interesting to be able to filter records before exporting to ADLS.
In some cases, we only need to export part of the data and not the entire table.

**Comment by DuttaSoumya** [comment]
Thanks @YvesDesrumaux!

May I know which table you want to export data from? And what stops you from exporting all the data?

I am afraid, at present a filtering capability does not exist. But I am thinking that there are two reasons why users may need such a filtering,
- [**Performance**] Because once the first export has been made (this typically may take longer), we assumed that the subsequent exports from the table are _quite fast_ if done daily. So, there was “no incentive” to not export ALL the data after the initial sync.
- [**Security**] Users may want to export only a part of the data into different storage accounts/ different containers in the storage account. In such a case, may I recommend that the table that is being exported is subjected to [security filtering](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/security/security-filters) to the credential that runs the export? It should be possible to [reset the export schema](https://github.com/microsoft/bc2adls/blob/main/businessCentral/src/ADLSESetupAPI.Page.al) and also [run the export](https://github.com/microsoft/bc2adls/blob/main/businessCentral/src/ADLSERunAPI.Page.al) on bc2adls through external automations via the API pages invoked by different user accounts.

I could not find any other justification to apply filtering on the data _before_ exporting it. And it seems to me that both of the above issues can usually be overcome, as stated above. So let me give a shout to the community of `bc2adls` users if they have encountered other reasons for filtering.

Best regards,
Dutta.

**Comment by YvesDesrumaux** [comment]
Hello Soumya,

We can imagine to have several companies that want to share business data of the common activities.

The simplest example is that the companies have common items and locals items. Local items outnumber common ones and are not necessary.
This could be inherit to inventory, sales document...

It could be great to apply table filters directly from setting.

Cordialement / Best regards

Yves DESRUMAUX - isatech
Tél : +33 185 651 681

De : Soumya Dutta ***@***.***>
Envoyé : mercredi 15 février 2023 11:33
À : microsoft/bc2adls ***@***.***>
Cc : Yves DESRUMAUX ***@***.***>; Mention ***@***.***>
Objet : Re: [microsoft/bc2adls] Filtering Record before exporting to ADLS (Issue #94)


Thanks @YvesDesrumaux<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FYvesDesrumaux&data=05%7C01%7Cyves.desrumaux%40isatech.fr%7Cb09ac27e0ff84967fd2508db0f3ffa79%7C599742606d1749d7b4921c295832012e%7C0%7C0%7C638120539698114529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=42Iy3VNU3fTf4u8pmbheFCBO1uF7OsDu2fstu1mXUto%3D&reserved=0>!

May I know which table you want to export data from? And what stops you from exporting all the data?

I am afraid, at present a filtering capability does not exist. But I am thinking that there are two reasons why users may need such a filtering,

  *   [Performance] Because once the first export has been made (this typically may take longer), we assumed that the subsequent exports from the table are quite fast if done daily. So, there was "no incentive" to not export ALL the data after the initial sync.
  *   [Security] Users may want to export only a part of the data into different storage accounts/ different containers in the storage account. In such a case, may I recommend that the table that is being exported is subjected to security filtering<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdynamics365%2Fbusiness-central%2Fdev-itpro%2Fsecurity%2Fsecurity-filters&data=05%7C01%7Cyves.desrumaux%40isatech.fr%7Cb09ac27e0ff84967fd2508db0f3ffa79%7C599742606d1749d7b4921c295832012e%7C0%7C0%7C638120539698114529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=n5tSoXMRnUVvCfl86lf%2FfZpWbY7TslFSK8KGUz6rqwg%3D&reserved=0> to the credential that runs the export? It should be possible to reset the export schema<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fbc2adls%2Fblob%2Fmain%2FbusinessCentral%2Fsrc%2FADLSESetupAPI.Page.al&data=05%7C01%7Cyves.desrumaux%40isatech.fr%7Cb09ac27e0ff84967fd2508db0f3ffa79%7C599742606d1749d7b4921c295832012e%7C0%7C0%7C638120539698114529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bfv8hot3MSWu3u3tzuqlloSVFJW5%2FZ15RHDxvig1fyc%3D&reserved=0> and also run the export<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fbc2adls%2Fblob%2Fmain%2FbusinessCentral%2Fsrc%2FADLSERunAPI.Page.al&data=05%7C01%7Cyves.desrumaux%40isatech.fr%7Cb09ac27e0ff84967fd2508db0f3ffa79%7C599742606d1749d7b4921c295832012e%7C0%7C0%7C638120539698114529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VNEEsYIINJmWRVs2WwStLbkwY%2BoatzvPP8IYvBp9WEc%3D&reserved=0> on bc2adls through external automations via the API pages invoked by different user accounts.

I could not find any other justification to apply filtering on the data before exporting it. And it seems to me that both of the above issues can usually be overcome, as stated above. So let me give a shout to the community of bc2adls users if they have encountered other reasons for filtering.

Best regards,
Dutta.

-
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fbc2adls%2Fissues%2F94%23issuecomment-1431106718&data=05%7C01%7Cyves.desrumaux%40isatech.fr%7Cb09ac27e0ff84967fd2508db0f3ffa79%7C599742606d1749d7b4921c295832012e%7C0%7C0%7C638120539698114529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LVLj7u3sQe%2FdefIL5Pfvmxu8qLrrfnkXomqgjEdouNI%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHFOWXSF6MAFYOEHG3F6ZS3WXSWEZANCNFSM6AAAAAAU3HPR7Q&data=05%7C01%7Cyves.desrumaux%40isatech.fr%7Cb09ac27e0ff84967fd2508db0f3ffa79%7C599742606d1749d7b4921c295832012e%7C0%7C0%7C638120539698114529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UTjiHx9rlluBrKaAtGu48D%2F3PO7Tk4wxMz4M8SazNs0%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

[https://www.isatech.fr/wp-content/uploads/2022/11/webinaire-securité-ms365.jpg]<https://www.isatech.fr/webinaire-microsoft-365-comment-renforcer-la-securite-de-vos-datas/>
Les informations contenues dans ces documents et leurs fichiers joints peuvent être de nature confidentielle et couvertes par le secret des correspondances (article 226-15 du Code Pénal). Elles sont destinées à l'usage exclusif du destinataire indiqué ci-dessus. Si vous n'êtes pas le destinataire, vous êtes par la présente avisés que toute divulgation, reproduction, distribution ou autre utilisation de cette communication est strictement interdite. Si vous recevez cette communication par erreur, veuillez-nous en aviser sans délais, détruire toutes les copies et la supprimer de votre système informatique. Afin de contribuer au respect de l'environnement, merci de n'imprimer cet email que si nécessaire.

**Comment by DuttaSoumya** [comment]
Hi @YvesDesrumaux,

Just for me to understand better, what is the real objection to sending the local entities as well to the lake, even though they may not be necessary? Why not have a full backup instead of a partial one, when possible?

In this particular case, you may apply the Security filtering idea discussed above for the field which you would have filtered on to differentiate the common from the local items. And then allow the user who runs the export to only access the "common" records. Thereby you should see that only the common items get exported to the lake!

In theory, it is possible to apply filtering to the table on the [ADLSESetup](https://github.com/microsoft/bc2adls/blob/main/businessCentral/src/ADLSESetupTables.Page.al) page itself using the [FilterPageBuilder](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/filterpagebuilder/filterpagebuilder-data-type) construct, and then store the filters (using [GetView](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/filterpagebuilder/filterpagebuilder-getview-method)) as a new field on the [ADLSETable](https://github.com/microsoft/bc2adls/blob/main/businessCentral/src/ADLSETable.Table.al) record. But there are repercussions! Suppose you have set a table to be exported with certain filters and have performed an export. Now, you change the filters to encompass a larger set of records. The next run will skip exporting those records that were,
1. not part of the previous filtered set and
1. modified before the highest timestamp (row number) of the previously exported record. 
 
Accounting for such complications make us shy to build the filtering capability- and therefore we need to understand the real use cases for filtering here. Nevertheless, if you have a tested solution for this you are free to contribute on this GitHub by creating your own pull request.

Best regards,
Dutta.

**Comment by DuttaSoumya** [comment]
Closing this out because of no response.
